### ISSUE TITLE
Error using service layer addon

### ISSUE THREAD

**Issue by mdjerad** [gvSIGAssociation/gvnix#17]
Hi !

Firstly, thank you for your work, you're genius !

I'm trying to generate the service layer for a WSDL using your service addon.
In gvnix, I'm using this command line :
* remote service import ws --class ~.metadata --wsdl "D:\\metadata.xml"

It fails with this error :
* Created SRC_MAIN_RESOURCES\dynamic-configuration.xml
* Created SRC_MAIN_JAVA\crmit\metadata
* Created SRC_MAIN_JAVA\crmit\metadata\Metadata.java
* Updated SRC_MAIN_JAVA\crmit\metadata\Metadata.java
* Updated ROOT\pom.xml [added repository https://gvnix.googlecode.com/svn/repo; ad
ded dependency org.gvnix:org.gvnix.service.roo.addon.annotations:1.4.1.RELEASE]
Updated ROOT\pom.xml [skipped dependency org.gvnix:org.gvnix.service.roo.addon.a
nnotations:1.4.1.RELEASE; added plugin org.apache.cxf:cxf-java2ws-plugin:${cxf.v
ersion}]
* Updated ROOT\pom.xml [added dependency org.apache.cxf:cxf-rt-frontend-jaxws:${cx
f.version}; added dependency org.apache.cxf:cxf-rt-transports-http:${cxf.version
}; added dependency org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.
* Final; added dependency org.springframework:spring-tx:${spring.version}; added p
roperty 'cxf.version' = '2.7.3'; added plugin org.apache.cxf:cxf-codegen-plugin:
${cxf.version}]
* Updated ROOT\pom.xml
* Generating sources ...
* Generating sources error !
* Undo manage ROOT\pom.xml
* Undo manage SRC_MAIN_JAVA\crmit\metadata\Metadata.java
* Undo create SRC_MAIN_JAVA\crmit\metadata\Metadata.java
* Undo create SRC_MAIN_JAVA\crmit\metadata
* Error generating web service sources
 
Can you help ?

Kind regards.

Mehdi

**Comment by jcagarcia** [comment]
Hi @mdjerad and thanks for your interest on gvNIX project,

Could you provide us your "log.roo" file and your wsdl file to be able to check your registered issue?

Regards and thank you again,

**Comment by mdjerad** [comment]
Hi !

Please find requested files in the following link :http://dl.free.fr/kZkrfxLGC

Regards,

Mehdi

**Comment by jcagarcia** [comment]
Hi again @mdjerad ,

I was testing your wsdl on gvNIX 1.4.1.RELEASE and works fine for me!

This is my *log.roo*:

````
project --topLevelPackage crmit.metadata
development mode
remote service import ws --class ~.metadata --wsdl file:///home/jcagarcia/Descargas/gvnix_service_issue/metadata.xml
````

Following structure will be generated:

````
├── log.roo
├── pom.xml
├── src
│   └── main
│       ├── java
│       │   └── crmit
│       │       └── metadata
│       │           ├── Metadata.java
│       │           └── Metadata_Roo_GvNix_WebServiceProxy.aj
│       └── resources
│           ├── dynamic-configuration.xml
│           ├── log4j.properties
│           └── META-INF
│               └── spring
│                   └── applicationContext.xml

````
Maybe you forgot to include 'file://' on WSDL location?

Try to use _development mode_ command before to see the complete error log on gvNIX shell and if the error persist provide it us!

Regards,

**Comment by mdjerad** [comment]
Hi,

I still have the same problem.
Here is the gvNIX shell results :

roo-gvNIX> development mode --enabled=true
Option 'enabled=true' is not available for this command. Use tab assist or the "
help" command to see the legal options
roo-gvNIX> development mode
Development mode set to true
roo-gvNIX> remote service import ws --class ~.metadata --wsdl file:///D://metada
ta.xml
Created SRC_MAIN_JAVA\crmit\metadata
5e7120f Created SRC_MAIN_JAVA\crmit\metadata\Metadata.java
ed353fc Updated SRC_MAIN_JAVA\crmit\metadata\Metadata.java
39b8560 Updated ROOT\pom.xml [added repository https://gvnix.googlecode.com/svn/
repo; added dependency org.gvnix:org.gvnix.service.roo.addon.annotations:1.4.1.R
ELEASE]
d716b78 Updated ROOT\pom.xml [skipped dependency org.gvnix:org.gvnix.service.roo
.addon.annotations:1.4.1.RELEASE; added plugin org.apache.cxf:cxf-java2ws-plugin
:${cxf.version}]
251c9e0 Updated ROOT\pom.xml [added dependency org.apache.cxf:cxf-rt-frontend-ja
xws:${cxf.version}; added dependency org.apache.cxf:cxf-rt-transports-http:${cxf
.version}; added dependency org.hibernate.javax.persistence:hibernate-jpa-2.0-ap
i:1.0.1.Final; added dependency org.springframework:spring-tx:${spring.version};
 added property 'cxf.version' = '2.7.3'; added plugin org.apache.cxf:cxf-codegen
-plugin:${cxf.version}]
27789fc Updated ROOT\pom.xml
Generating sources ...
Generating sources error !
Error generating web service sources
java.lang.IllegalStateException: Error generating web service sources
    at org.gvnix.service.roo.addon.ws.importt.WSImportMetadataProvider.getMetada
ta(WSImportMetadataProvider.java:202)
    at org.springframework.roo.classpath.itd.AbstractItdMetadataProvider.get(Abs
tractItdMetadataProvider.java:264)
    at org.springframework.roo.metadata.DefaultMetadataService.getInternal(Defau
ltMetadataService.java:212)
    at org.springframework.roo.metadata.DefaultMetadataService.evictAndGet(Defau
ltMetadataService.java:121)
    at org.springframework.roo.classpath.itd.AbstractItdMetadataProvider.notify(
AbstractItdMetadataProvider.java:601)
    at org.springframework.roo.metadata.DefaultMetadataService.notify(DefaultMet
adataService.java:325)
    at org.springframework.roo.metadata.internal.DefaultMetadataDependencyRegist
ry.notifyDownstream(DefaultMetadataDependencyRegistry.java:238)
    at org.springframework.roo.classpath.DefaultPhysicalTypeMetadataProvider.onF
ileEvent(DefaultPhysicalTypeMetadataProvider.java:250)
    at org.springframework.roo.file.monitor.polling.PollingFileMonitorService.pu
blish(PollingFileMonitorService.java:433)
    at org.springframework.roo.file.monitor.polling.PollingFileMonitorService.pu
blishRequestedFileEvents(PollingFileMonitorService.java:456)
    at org.springframework.roo.file.monitor.polling.PollingFileMonitorService.sc
anNotified(PollingFileMonitorService.java:660)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.do
Transactionally(DefaultProcessManager.java:335)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.ex
ecute(DefaultProcessManager.java:71)
    at org.springframework.roo.process.manager.ProcessManagerHostedExecutionStra
tegy.execute(ProcessManagerHostedExecutionStrategy.java:44)
    at org.springframework.roo.shell.AbstractShell.executeCommandImpl(AbstractSh
ell.java:242)
    at org.springframework.roo.shell.AbstractShell.executeCommand(AbstractShell.
java:149)
    at org.springframework.roo.shell.jline.JLineShell.promptLoop(JLineShell.java
:421)
    at org.springframework.roo.shell.jline.JLineShell.run(JLineShell.java:539)
    at java.lang.Thread.run(Unknown Source)
[Spring Roo Process Manager Background Polling Thread] 07c0a15 Updated ROOT\pom.
xml [skipped dependency org.gvnix:org.gvnix.service.roo.addon.annotations:1.4.1.
RELEASE]
[Spring Roo Process Manager Background Polling Thread] Generating sources ...
[Spring Roo Process Manager Background Polling Thread] Generating sources error
!
[Spring Roo Process Manager Background Polling Thread] Error generating web serv
ice sources
                                                       java.lang.IllegalStateExc
eption: Error generating web service sources
                                                           at org.gvnix.service.
roo.addon.ws.importt.WSImportMetadataProvider.getMetadata(WSImportMetadataProvid
er.java:202)
                                                           at org.springframewor
k.roo.classpath.itd.AbstractItdMetadataProvider.get(AbstractItdMetadataProvider.
java:264)
                                                           at org.springframewor
k.roo.metadata.DefaultMetadataService.getInternal(DefaultMetadataService.java:21
2)
                                                           at org.springframewor
k.roo.metadata.DefaultMetadataService.evictAndGet(DefaultMetadataService.java:12
1)
                                                           at org.springframewor
k.roo.classpath.itd.AbstractItdMetadataProvider.notify(AbstractItdMetadataProvid
er.java:601)
                                                           at org.springframewor
k.roo.metadata.DefaultMetadataService.notify(DefaultMetadataService.java:325)
                                                           at org.springframewor
k.roo.metadata.internal.DefaultMetadataDependencyRegistry.notifyDownstream(Defau
ltMetadataDependencyRegistry.java:238)
                                                           at org.springframewor
k.roo.classpath.DefaultPhysicalTypeMetadataProvider.onFileEvent(DefaultPhysicalT
ypeMetadataProvider.java:250)
                                                           at org.springframewor
k.roo.file.monitor.polling.PollingFileMonitorService.publish(PollingFileMonitorS
ervice.java:433)
                                                           at org.springframewor
k.roo.file.monitor.polling.PollingFileMonitorService.scanAll(PollingFileMonitorS
ervice.java:646)
                                                           at org.springframewor
k.roo.process.manager.internal.DefaultProcessManager.doTransactionally(DefaultPr
ocessManager.java:322)
                                                           at org.springframewor
k.roo.process.manager.internal.DefaultProcessManager.backgroundPoll(DefaultProce
ssManager.java:257)
                                                           at org.springframewor
k.roo.process.manager.internal.DefaultProcessManager.timerBasedPoll(DefaultProce
ssManager.java:166)
                                                           at org.springframewor
k.roo.process.manager.internal.DefaultProcessManager$2.run(DefaultProcessManager
.java:219)
                                                           at java.lang.Thread.r
un(Unknown Source)
roo-gvNIX>

**Comment by jcagarcia** [comment]
Hi @mdjerad 

Seems like gvNIX is not locating your WSDL file on the sepecified path *file:///D://metada
ta.xml*

Check correct URI format on Windows and try again:

http://blogs.msdn.com/b/ie/archive/2006/12/06/file-uris-in-windows.aspx

Regards,

**Comment by mdjerad** [comment]
According to the document, correct URI is :
file:///D:/metadata.xml

I tried with this format but I have the exact same problem...

When I use a filename that doesn't exists, I have another message (more explicit) :
roo-gvNIX> remote service import ws --class ~.sfmetadata --wsdl file:///D:/metad
ata_TEST.xml
The format of the wsdl has errors: file:///D:/metadata_TEST.xml
java.io.FileNotFoundException: D:\metadata_TEST.xml (Le fichier spécifié est int
rouvable)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(Unknown Source)
    at java.io.FileInputStream.<init>(Unknown Source)
    at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source
)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEnti
ty(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVe
rsion(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unkno
wn Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unkno
wn Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source
)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source
)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown
 Source)
    at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
    at org.gvnix.service.roo.addon.security.SecurityServiceImpl.getWsdl(Security
ServiceImpl.java:214)
    at org.gvnix.service.roo.addon.security.SecurityServiceImpl.getWsdl(Security
ServiceImpl.java:440)
    at org.gvnix.service.roo.addon.ws.importt.WSImportOperationsImpl.addImportAn
notation(WSImportOperationsImpl.java:103)
    at org.gvnix.service.roo.addon.ServiceCommands.serviceImport(ServiceCommands
.java:269)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.roo.process.manager.ProcessManagerHostedExecutionStra
tegy$1.callback(ProcessManagerHostedExecutionStrategy.java:47)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.do
Transactionally(DefaultProcessManager.java:325)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.ex
ecute(DefaultProcessManager.java:71)
    at org.springframework.roo.process.manager.ProcessManagerHostedExecutionStra
tegy.execute(ProcessManagerHostedExecutionStrategy.java:44)
    at org.springframework.roo.shell.AbstractShell.executeCommandImpl(AbstractSh
ell.java:242)
    at org.springframework.roo.shell.AbstractShell.executeCommand(AbstractShell.
java:149)
    at org.springframework.roo.shell.jline.JLineShell.promptLoop(JLineShell.java
:421)
    at org.springframework.roo.shell.jline.JLineShell.run(JLineShell.java:539)
    at java.lang.Thread.run(Unknown Source)
There is not access to the wsdl: file:///D:/metadata_TEST.xml
java.lang.IllegalStateException: There is not access to the wsdl: file:///D:/met
adata_TEST.xml
    at org.gvnix.service.roo.addon.security.SecurityServiceImpl.getWsdl(Security
ServiceImpl.java:236)
    at org.gvnix.service.roo.addon.security.SecurityServiceImpl.getWsdl(Security
ServiceImpl.java:440)
    at org.gvnix.service.roo.addon.ws.importt.WSImportOperationsImpl.addImportAn
notation(WSImportOperationsImpl.java:103)
    at org.gvnix.service.roo.addon.ServiceCommands.serviceImport(ServiceCommands
.java:269)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.roo.process.manager.ProcessManagerHostedExecutionStra
tegy$1.callback(ProcessManagerHostedExecutionStrategy.java:47)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.do
Transactionally(DefaultProcessManager.java:325)
    at org.springframework.roo.process.manager.internal.DefaultProcessManager.ex
ecute(DefaultProcessManager.java:71)
    at org.springframework.roo.process.manager.ProcessManagerHostedExecutionStra
tegy.execute(ProcessManagerHostedExecutionStrategy.java:44)
    at org.springframework.roo.shell.AbstractShell.executeCommandImpl(AbstractSh
ell.java:242)
    at org.springframework.roo.shell.AbstractShell.executeCommand(AbstractShell.
java:149)
    at org.springframework.roo.shell.jline.JLineShell.promptLoop(JLineShell.java
:421)
    at org.springframework.roo.shell.jline.JLineShell.run(JLineShell.java:539)
    at java.lang.Thread.run(Unknown Source)

Regards

**Comment by jcagarcia** [comment]
Hi @mdjerad 

I'll check it on a Windows machine to see if there's some error related with windows paths...

Regards,

**Comment by mdjerad** [comment]
Hi,

do you have any news regarding my case ?

Thanks !

Regards

Mehdi

**Comment by lemartva** [comment]
Hi, I have a similar issue, but when I set on debug mode , the console never showed any information.

I'm working with gvNIX 1.4.1.RELEASE distribution and sts-3.6.4.RELEASE

this is the command:

remote service import ws --wsdl http://www.restfulwebservices.net/wcf/UNSPSCService.svc?wsdl --class ~.services.UNSPSC

this is the result:

roo-gvNIX> 
development mode
Development mode set to true
roo-gvNIX> 
remote service import ws --wsdl http://www.restfulwebservices.net/wcf/UNSPSCService.svc?wsdl --class ~.services.UNSPSC
7e0ec85 Created SRC_MAIN_JAVA/com/sic/presupuesto/services/UNSPSC.java
3b4fb36 Updated SRC_MAIN_JAVA/com/sic/presupuesto/services/UNSPSC.java
Generating sources ...
Generating sources error !
Error generating web service sources
roo-gvNIX> 

Thanks in advance for any help you are able to provide.

**Comment by jcagarcia** [comment]
Hi @mdjerad

Sorry for the delay.

Could you provide your **metadata.xml** file again? I'm not able to download it to test it on a windows machine.

Regards,
